# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GitHubViewer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GitHubViewer
  
  pod 'AFNetworking', '~> 3.1'

  pod 'MBProgressHUD', '~> 1.0'

  pod 'DCKeyValueObjectMapping', '~> 1.5'

  pod 'SDWebImage', '~> 3.8'

  target 'GitHubViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
